"""add laer

Revision ID: d13ee7bd0845
Revises: e85af8160c23
Create Date: 2023-07-17 09:51:32.299487

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd13ee7bd0845'
down_revision = 'e85af8160c23'
branch_labels = ()
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('laer',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('code', sa.UnicodeText(), nullable=True),
    sa.Column('metal', sa.SmallInteger(), nullable=True),
    sa.Column('plastic_post_consumer', sa.SmallInteger(), nullable=True),
    sa.Column('plastic_post_industry', sa.SmallInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('laer')
    # ### end Alembic commands ###
