"""initial models

Revision ID: e85af8160c23
Revises: 
Create Date: 2023-06-20 16:59:15.806761

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e85af8160c23'
down_revision = None
branch_labels = ('default',)
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.UnicodeText(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('icecat',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('date', sa.BigInteger(), nullable=False),
    sa.Column('url', sa.UnicodeText(), nullable=True),
    sa.Column('title', sa.UnicodeText(), nullable=True),
    sa.Column('image', sa.UnicodeText(), nullable=True),
    sa.Column('brand', sa.UnicodeText(), nullable=True),
    sa.Column('brand_logo', sa.UnicodeText(), nullable=True),
    sa.Column('product_name', sa.UnicodeText(), nullable=True),
    sa.Column('product_serie', sa.UnicodeText(), nullable=True),
    sa.Column('long_product_name', sa.UnicodeText(), nullable=True),
    sa.Column('brand_part_code', sa.UnicodeText(), nullable=True),
    sa.Column('chassis', sa.UnicodeText(), nullable=True),
    sa.Column('family', sa.UnicodeText(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('guide',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('date', sa.BigInteger(), nullable=False),
    sa.Column('url', sa.UnicodeText(), nullable=True),
    sa.Column('title', sa.UnicodeText(), nullable=True),
    sa.Column('image_guid', sa.UnicodeText(), nullable=True),
    sa.Column('category_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('guide')
    op.drop_table('icecat')
    op.drop_table('category')
    # ### end Alembic commands ###
