"""add laer computer mix

Revision ID: f8e4000bc361
Revises: d13ee7bd0845
Create Date: 2023-07-17 10:22:59.806557

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8e4000bc361'
down_revision = 'd13ee7bd0845'
branch_labels = ()
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('computer_laer',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.UnicodeText(), nullable=False),
    sa.Column('laer_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['laer_id'], ['laer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('computer_laer')
    # ### end Alembic commands ###
